### ISSUE TITLE
No mixin named ease0ut

### ISSUE THREAD

**Issue by hnostdal** [bradtraversy/modern_portfolio#9]
I get errors when trying to save
"status": 1,
  "file": "C:/users/yo/desktop/code/modern_portfolio/sccs/_menu.scss",
  "line": 8,
  "column": 12,
  "message": "no mixin named easeOut",
  "formatted": "Error: no mixin named easeOut\n        on line 8 of sccs/_menu.scss\n        from line 2 of sccs/main.scss\n>>   @include easeOut;\r\n   -----------^\n"

I have checked the code vs yours on github 100 times..

**Comment by hnostdal** [comment]
lol, it is very hard to see the difference between easeOut and ease0ut

**Comment by AbdulBasee** [comment]
In my case I had put in  @include ease-out which was causing this issue.Then when I changed it to @include easeOut; , it worked for me.
Change your one to @include easeOut;

**Comment by DeshanDev** [comment]
I tried both. Not working. Only Errors & Not showing The Hamburger Menu Icon (On windows 10 pro 64 bit)

----Code Snippet No 1----

// Menu Button
.menu-btn {
    position: absolute;
    z-index: 3;
    right: 35px;
    top: 35px;
    cursor: pointer;
    @include ease-out;

    .btn-line {
        width: 28px;
        height: 3px;
        margin: 0 0 5px 0;
        background: #fff;
        @include ease-out;
    }
}

----Code Snippet No 2----

.menu-btn {
    position: absolute;
    z-index: 3;
    right: 35px;
    top: 35px;
    cursor: pointer;
    @include easeOut;

    .btn-line {
        width: 28px;
        height: 3px;
        margin: 0 0 5px 0;
        background: #fff;
        @include easeOut;
    }
}

----Code Snippet No 3----

.menu-btn {
    position: absolute;
    z-index: 3;
    right: 35px;
    top: 35px;
    cursor: pointer;
    @include easeout;

    .btn-line {
        width: 28px;
        height: 3px;
        margin: 0 0 5px 0;
        background: #fff;
        @include easeout;
    }
}

----Code Snippet No 4----

.menu-btn {
    position: absolute;
    z-index: 3;
    right: 35px;
    top: 35px;
    cursor: pointer;
    @include ease0ut;

    .btn-line {
        width: 28px;
        height: 3px;
        margin: 0 0 5px 0;
        background: #fff;
        @include ease0ut;
    }
}
